export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGIN_SUCCEEDED = "USER_LOGIN_SUCCEEDED"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"

// students
export const FETCH_STUDENTS = "FETCH_STUDENTS"
export const FETCH_STUDENTS_SUCCEEDED = "FETCH_STUDENTS_SUCCEEDED"
export const FETCH_STUDENTS_FAILED = "FETCH_STUDENTS_FAILED"