export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGIN_SUCCEEDED = "USER_LOGIN_SUCCEEDED"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"

// students
export const FETCH_STUDENTS = "FETCH_STUDENTS"
export const FETCH_STUDENTS_SUCCEEDED = "FETCH_STUDENTS_SUCCEEDED"
export const FETCH_STUDENTS_FAILED = "FETCH_STUDENTS_FAILED"

export const ADD_STUDENTS = "ADD_STUDENTS"
export const ADD_STUDENTS_SUCCEEDED = "ADD_STUDENTS_SUCCEEDED"
export const ADD_STUDENTS_FAILED = "ADD_STUDENTS_FAILED"

export const DELETE_STUDENT = "DELETE_STUDENT"
export const DELETE_STUDENT_SUCCEEDED = "DELETE_STUDENT_SUCCEEDED"
export const DELETE_STUDENT_FAILED = "DELETE_STUDENT_FAILED"